version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
python:
  version: "3.10"
  install:
    - method: pip
      path: "."
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
